---
title: "Pharmacy-Managed Warfarin Dosing Service Analysis for Fiscal Year 2017"
author: "Brian Gulbis, PharmD, BCPS"
date: "August 28, 2017"
output:
  tufte::tufte_handout:
    latex_engine: pdflatex
link-citations: yes
---

```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, echo = FALSE, message = FALSE, warning = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
```

```{r data, message=FALSE}
library(tidyverse)
library(lubridate)
library(forcats)
library(broom)
library(themebg)

x <- dirr::get_rds("../data/tidy")
```

```{r, fig.cap="Warfarin managed by Pharmacy Dosing Service compared with traditional management"}
data_timeseries_location %>%
    filter(fy == 2016 | fy == 2017) %>%
    group_by(week) %>%
    summarize_at(c("pharmacy", "traditional"), sum, na.rm = TRUE) %>%
    gather(group, num, pharmacy, traditional) %>%
    ggplot(aes(x = week, y = num)) +
    geom_line(aes(linetype = group)) +
    geom_smooth(aes(linetype = group), method = "lm", color = "black", se = FALSE) +
    scale_x_datetime("", date_labels = "%b %Y") +
    ylab("Weekly Patients") +
    scale_linetype_discrete("", labels = c("Pharmacy", "Traditional")) +
    theme_bg() +
    theme(legend.position = "top")
```

```{r, fig.cap="Top 15 hospital units utilizing warfarin", fig.height=4.5}
data_timeseries_location %>%
    filter(fy == 2017) %>%
    group_by(order.location) %>%
    summarize_at(c("pharmacy", "traditional"), sum, na.rm = TRUE) %>%
    mutate(total = pharmacy + traditional) %>%
    arrange(desc(total)) %>%
    top_n(15, total) %>%
    gather(group, num, pharmacy, traditional) %>%
    mutate_at("order.location", as_factor) %>%
    mutate_at("order.location", fct_rev) %>%
    ggplot(aes(x = order.location, y = num, fill = group)) +
    geom_bar(stat = "identity") +
    xlab("Hospital Unit") +
    ylab("Warfarin Doses Administered") +
    scale_fill_manual("", values = c("#636363", "#bdbdbd"), labels = c("Pharmacy", "Traditional")) +
    coord_flip() +
    theme_bg() +
    theme(legend.position = "top")
```

```{r, fig.cap="Warfarin indications for patients managed by pharmacy and traditional"}
data_warfarin %>%
    filter(warfarin_start >= mdy("7/1/2016", tz = "US/Central"),
           warfarin_start <= mdy("6/30/2017", tz = "US/Central")) %>%
    group_by(group) %>%
    summarize_if(is.logical, funs(mean(., na.rm = TRUE) * 100)) %>%
    gather(indication, val, afib:other) %>%
    arrange(group, desc(val)) %>%
    mutate_at("indication", fct_inorder) %>%
    mutate_at("indication", fct_rev) %>%
    filter(val > 0) %>%
    ggplot(aes(x = indication, y = val, fill = group)) +
    geom_bar(stat = "identity", position = "dodge") +
    # xlab("Indication") +
    scale_x_discrete("Indication", labels = c("Hypercoaguable", "VAD", "Stroke", "Other", "Thrombus", "PE", "Valve", "DVT", "A.fib")) +
    ylab("Patients (%)") +
    scale_fill_manual("", values = c("#636363", "#bdbdbd"), labels = c("Pharmacy", "Traditional")) +
    coord_flip() +
    theme_bg(yticks = FALSE) +
    theme(legend.position = "top")
```

```{r, fig.cap="Distribution of warfarin dose by day of therapy"}
data_daily %>%
    ungroup() %>%
    filter(warfarin_day <= 7,
           med.datetime >= mdy("7/1/2016", tz = "US/Central"),
           med.datetime <= mdy("6/30/2017", tz = "US/Central")) %>%
    left_join(data_warfarin[c("millennium.id", "group", "initiation", "indication_group")], by = "millennium.id") %>%
    mutate_at("warfarin_day", as.integer) %>%
    mutate_at("warfarin_day", factor) %>%
    ggplot(aes(x = warfarin_day, y = med.dose, fill = group)) +
    geom_boxplot() +
    xlab("Day of therapy") +
    ylab("Warfarin dose (mg)") +
    scale_fill_manual("", values = c("#636363", "#bdbdbd"), labels = c("Pharmacy", "Traditional")) +
    theme_bg() +
    theme(legend.position = "top")
```

```{r, fig.cap="INR response during the first 7 days of warfarin therapy"}
data_daily %>%
    ungroup() %>%
    filter(warfarin_day <= 7,
           med.datetime >= mdy("7/1/2016", tz = "US/Central"),
           med.datetime <= mdy("6/30/2017", tz = "US/Central"),
           !is.na(inr)) %>%
    left_join(data_warfarin[c("millennium.id", "group", "initiation", "indication_group")], by = "millennium.id") %>%
    mutate_at("warfarin_day", as.numeric) %>%
    ggplot(aes(x = warfarin_day, y = inr, linetype = group)) +
    geom_smooth(color = "black") +
    scale_x_continuous("Day of therapy", breaks = seq(1, 7, 1)) +
    ylab("INR") +
    scale_linetype_discrete("", labels = c("Pharmacy", "Traditional")) +
    theme_bg() +
    theme(legend.position = "top")
```

```{r}
    
```


# Safety Assessment

```{r}
tbl_hgb_drop <- data_hgb_drop %>%
    inner_join(data_warfarin[c("millennium.id", "group", "warfarin_start")], by = "millennium.id") %>%
    filter(warfarin_start >= mdy("7/1/2016", tz = "US/Central"),
           warfarin_start <= mdy("6/30/2017", tz = "US/Central")) %>%
    group_by(group) %>%
    summarize_at("hgb_drop", mean) %>%
    mutate_at("hgb_drop", funs(. * 100)) %>%
    spread(group, hgb_drop) %>%
    mutate(Outcome = "Hgb drop") %>%
    select(Outcome, Pharmacy = pharmacy, Traditional = traditional) 

knitr::kable(tbl_hgb_drop, digits = 1, caption = "Hemoglobin decrease by >/= 2 g/dL within a 48-hour period")
```



* Transfusion
* Readmission
